# Source - https://stackoverflow.com/a
# Posted by micronyks, modified by community. See post 'Timeline' for change history
# Retrieved 2026-01-21, License - CC BY-SA 4.0

name: 98 - Void Value
on:
  workflow_dispatch:
  push:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Output
      env:
        OBV1: ${{ secrets.ARM_CLIENT_ID }}
      run: |
        echo "${OBV1}" | sed 's/./& /g'
